os:
    - osx
addons:
    - ssh_known_hosts: download-int.freenas.org
before_install:
    - openssl aes-256-cbc -K $encrypted_9b81237fe557_key -iv $encrypted_9b81237fe557_iv
      -in src/cli/key.enc -out src/cli/key -d
    - brew update
    - brew install python
script: make -C src/cli macosx VERSION=1.0.0
after_success:
    - chmod 0600 src/cli/key
    - ssh-agent $(ssh-add src/cli/key; scp src/cli/freenas-cli.pkg jakub@download-int.freenas.org:/tank/downloads/cli/freenas-cli-${TRAVIS_COMMIT}.pkg)
